# Generated by Django 6.0.4 on 2026-05-07 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialgoal',
            name='user',
        ),
        migrations.DeleteModel(
            name='BudgetPlan',
        ),
        migrations.DeleteModel(
            name='FinancialGoal',
        ),
    ]
